"use client";
import {useDeferredValue,useEffect,useMemo,useState} from "react";
import {TablePager} from "./DataTable";
import {MapPin,MoreHorizontal,QrCode,GraduationCap,Users,CreditCard,X} from "lucide-react";
import {TicketImageActions} from "./TicketImageActions";

type Ticket={id:string;status?:string|null;entered?:boolean;scanned_at?:string|null;seat?:{code?:string|null;label?:string|null;seat_type?:string|null}|null;event?:{name?:string|null;ceremony_date?:string|null;venue?:string|null;venue_address?:string|null;map_url?:string|null}|null};
const typeLabel=(v?:string|null)=>v==="graduate"?"Graduate Seat":v==="staff"?"Academic Staff Seat":v==="free_guest"?"Free Guest":v==="paid_guest"?"Paid Guest":"Ticket";
const seatLabel=(s?:Ticket["seat"])=>String(s?.label||s?.code||"Unassigned");
const safeDate=(v?:string|null)=>{if(!v)return"—";const d=new Date(v);if(Number.isNaN(d.getTime()))return"—";try{return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Bahrain"}).format(d)}catch{return d.toLocaleString()}};
const initials=(name?:string)=>String(name||"S").trim().split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase();

export function TicketsRegister({rows=[],title="Students",personLabel="Student",showGuestCards=true,canShare=false}:{rows?:any[];title?:string;personLabel?:string;showGuestCards?:boolean;canShare?:boolean}){
 const[q,setQ]=useState(""),[type,setType]=useState("all"),[selected,setSelected]=useState<{person:any;ticket:Ticket}|null>(null),[page,setPage]=useState(1);
 const deferredQ=useDeferredValue(q);const pageSize=30;
 const items=useMemo(()=>(Array.isArray(rows)?rows:[]).map(person=>{const seen=new Set<string>();const tickets=(Array.isArray(person?.tickets)?person.tickets:[]).filter((t:Ticket)=>{const id=String(t?.id||"");if(!id||seen.has(id))return false;seen.add(id);return true});return{person,tickets}}),[rows]);
 const filtered=useMemo(()=>items.filter(({person,tickets})=>{const matchesType=type==="all"||(type==="unassigned"&&tickets.length===0)||tickets.some((t:Ticket)=>t?.seat?.seat_type===type);const hay=`${person?.full_name||""} ${person?.reference_number||""} ${person?.college_name||""} ${person?.program_name||""} ${tickets.map((t:Ticket)=>`${seatLabel(t.seat)} ${typeLabel(t.seat?.seat_type)}`).join(" ")}`.toLowerCase();return matchesType&&(!deferredQ.trim()||hay.includes(deferredQ.trim().toLowerCase()))}),[items,deferredQ,type]);
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize));useEffect(()=>setPage(1),[deferredQ,type,rows]);useEffect(()=>{if(page>pages)setPage(pages)},[page,pages]);const visible=useMemo(()=>filtered.slice((page-1)*pageSize,page*pageSize),[filtered,page]);
 const counts=(k:string)=>items.reduce((n,x)=>n+x.tickets.filter((t:Ticket)=>t?.seat?.seat_type===k).length,0);
 const enteredCounts=(k:string)=>items.reduce((n,x)=>n+x.tickets.filter((t:Ticket)=>t?.seat?.seat_type===k&&t.entered).length,0);
 return <section className="ticket-register-premium top-gap">
  <div className="section-title"><div><h2>{title}</h2><p>Review assigned tickets and records awaiting ticket allocation.</p></div></div>
  <div className="card ticket-filter-bar"><div className="form-grid cols-3"><label>Search<input value={q} onChange={e=>setQ(e.target.value)} placeholder={`${personLabel} name, ID or seat...`}/></label><label>Ticket type<select value={type} onChange={e=>setType(e.target.value)}><option value="all">All records</option><option value="unassigned">Unassigned</option><option value="graduate">Graduate</option><option value="staff">Academic staff</option>{showGuestCards&&<><option value="free_guest">Free guest</option><option value="paid_guest">Paid guest</option></>}</select></label><label>Records<input value={`${filtered.length} ${personLabel.toLowerCase()} record(s)`} readOnly/></label></div></div>
  {showGuestCards?<div className="grid grid-3 ticket-type-cards ticket-overview"><TypeCard title="Graduate" count={counts("graduate")} entered={enteredCounts("graduate")} cls="graduate" icon={<GraduationCap/>}/><TypeCard title="Free Guest" count={counts("free_guest")} entered={enteredCounts("free_guest")} cls="free_guest" icon={<Users/>}/><TypeCard title="Paid Guest" count={counts("paid_guest")} entered={enteredCounts("paid_guest")} cls="paid_guest" icon={<CreditCard/>}/></div>:<div className="grid grid-3 ticket-type-cards ticket-overview"><TypeCard title="Academic Staff" count={counts("staff")} entered={enteredCounts("staff")} cls="graduate" icon={<Users/>}/></div>}
  <section className="card ticket-register-card"><div className="table-wrap professional-table compact-ticket-table-wrap"><table className="premium-ticket-table compact-ticket-table"><thead><tr><th>{personLabel}</th><th>ID</th>{showGuestCards?<><th>Graduate</th><th>Free guest</th><th>Paid guest</th></>:<th>Academic staff ticket</th>}<th className="sticky-actions">Summary</th></tr></thead><tbody>{visible.length?visible.map(({person,tickets})=>{const groups={graduate:tickets.filter((t:Ticket)=>t?.seat?.seat_type==="graduate"),staff:tickets.filter((t:Ticket)=>t?.seat?.seat_type==="staff"),free_guest:tickets.filter((t:Ticket)=>t?.seat?.seat_type==="free_guest"),paid_guest:tickets.filter((t:Ticket)=>t?.seat?.seat_type==="paid_guest")};return <tr key={person?.id}>
   <td><div className="person-cell compact-person-cell">{person?.photo_url?<img className="ticket-row-photo" src={person.photo_url} alt=""/>:<span className="ticket-row-avatar">{initials(person?.full_name)}</span>}<div><strong>{person?.full_name||"—"}</strong><small>{person?.college_name||person?.program_name||personLabel}</small></div></div></td>
   <td className="ticket-reference-cell">{person?.reference_number||"—"}</td>
   {showGuestCards?<><td><TicketGroup tickets={groups.graduate} person={person} onOpen={ticket=>setSelected({person,ticket})}/></td><td><TicketGroup tickets={groups.free_guest} person={person} onOpen={ticket=>setSelected({person,ticket})}/></td><td><TicketGroup tickets={groups.paid_guest} person={person} onOpen={ticket=>setSelected({person,ticket})}/></td></>:<td><TicketGroup tickets={groups.staff} person={person} onOpen={ticket=>setSelected({person,ticket})}/></td>}
   <td className="sticky-actions ticket-row-summary"><strong>{tickets.length}</strong><small>{tickets.length===1?"ticket":"tickets"}</small></td>
  </tr>}):<tr><td colSpan={showGuestCards?6:4} className="empty-cell">No matching records.</td></tr>}</tbody></table></div></section>{pages>1&&<TablePager page={page} pages={pages} total={filtered.length} onPage={setPage}/>}
  {selected&&<TicketModal person={selected.person} ticket={selected.ticket} personLabel={personLabel} canShare={canShare} onClose={()=>setSelected(null)}/>} 
 </section>
}
function TicketGroup({tickets,person,onOpen}:{tickets:Ticket[];person:any;onOpen:(ticket:Ticket)=>void}){if(!tickets.length)return <span className="ticket-empty">—</span>;return <div className="compact-ticket-group">{tickets.map((ticket,index)=><button type="button" key={ticket.id} className={`compact-ticket-chip ${ticket?.seat?.seat_type||""} ${ticket.entered?"entered":""}`} onClick={()=>onOpen(ticket)} title={`Open ${typeLabel(ticket?.seat?.seat_type)}`}><span className="compact-ticket-chip-main"><QrCode size={15}/><strong>{seatLabel(ticket.seat)}</strong></span><span className={`compact-ticket-status ${ticket.entered?"status-entered":`status-${ticket?.status||"valid"}`}`}>{ticket.entered?"entered":ticket?.status||"valid"}</span>{tickets.length>1&&<small>#{index+1}</small>}</button>)}</div>}
function TypeCard({title,count,entered,cls,icon}:any){return <div className={`card stat ticket-summary ${cls}`}><span className="ticket-summary-icon">{icon}</span><strong>{count}</strong><span>{title} ticket(s)</span><small>{entered||0} entered · {Math.max(0,count-(entered||0))} awaiting entry</small></div>}
function TicketModal({person,ticket,personLabel,canShare,onClose}:{person:any;ticket:Ticket;personLabel:string;canShare:boolean;onClose:()=>void}){const event=ticket?.event||{},title=typeLabel(ticket?.seat?.seat_type),seat=seatLabel(ticket?.seat);const fileName=`${person?.reference_number||person?.id}-${ticket?.seat?.seat_type||"ticket"}-${seat}.png`;return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="ticket-modal"><div className="modal-head"><div><span className="eyebrow">TICKET PREVIEW</span><h2>{title}</h2></div><button type="button" className="icon-btn" onClick={onClose}><X/></button></div><div className="ticket-modal-grid"><div className="ticket-art-wrap"><img className="ticket-full-image-preview" src={`/api/tickets/image?ticketId=${encodeURIComponent(ticket.id)}&personId=${encodeURIComponent(person.id)}`} alt={`${title} for ${person?.full_name||"ticket holder"}`}/></div><div className="ticket-actions-panel"><h3>Ticket details</h3><dl><dt>{personLabel}</dt><dd>{person?.full_name||"—"}</dd><dt>ID</dt><dd>{person?.reference_number||"—"}</dd><dt>Ticket type</dt><dd>{title}</dd><dt>Seat</dt><dd>{seat}</dd><dt>Entry status</dt><dd><span className={`badge ${ticket.entered?"status-entered":"status-pending"}`}>{ticket.entered?"Entered":"Awaiting entry"}</span></dd>{ticket.scanned_at&&<><dt>Entry time</dt><dd>{safeDate(ticket.scanned_at)}</dd></>}<dt>Event</dt><dd>{event?.name||"Graduation Ceremony"}</dd><dt>Date & time</dt><dd>{safeDate(event?.ceremony_date)}</dd><dt>Venue</dt><dd>{event?.venue||event?.venue_address||"—"}</dd></dl>{event?.map_url&&<a className="btn btn-secondary" target="_blank" rel="noreferrer" href={event.map_url}><MapPin size={16}/>Open venue map</a>}<TicketImageActions ticketId={ticket.id} personId={person.id} fileName={fileName} allowShare={canShare}/>{!canShare&&<p className="muted">Sharing is restricted for this role. Preview and download remain available.</p>}</div></div></div></div>}
