import {createAdminClient} from "@/lib/supabase/admin";
import {sendGraphEmail,EmailAttachment} from "@/lib/email";
import {escapeHtml} from "@/lib/message-templates";
import {buildTicketCardPng,ticketTypeLabel} from "@/lib/ticket-card";

function directions(event:any){if(event.latitude!=null&&event.longitude!=null)return`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${event.latitude},${event.longitude}`)}`;if(event.map_url)return event.map_url;return`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(event.venue_address||event.venue||"")}`}
export async function sendBookingConfirmation(bookingId:string){
 const admin=createAdminClient();const{data:booking,error}=await admin.from("bookings").select("id,event_id,user_id,person_id,status,total_bhd,organization_id").eq("id",bookingId).single();if(error||!booking)throw new Error(error?.message||"Booking not found");
 const[{data:event},{data:tickets},{data:org}]=await Promise.all([admin.from("events").select("id,name,ceremony_date,venue,venue_address,map_url,latitude,longitude").eq("id",booking.event_id).single(),admin.from("tickets").select("id,qr_token,seat_id,status").eq("booking_id",booking.id).order("created_at"),admin.from("organizations").select("name").eq("id",booking.organization_id).maybeSingle()]);if(!event)throw new Error("Event not found");
 let person:any=null;if(booking.person_id){person=(await admin.from("people_directory").select("id,full_name,email,reference_number,person_type,photo_url").eq("id",booking.person_id).maybeSingle()).data}else if(booking.user_id){person=(await admin.from("people_directory").select("id,full_name,email,reference_number,person_type,photo_url").eq("profile_id",booking.user_id).maybeSingle()).data;if(!person)person=(await admin.from("profiles").select("id,full_name,email,reference_number").eq("id",booking.user_id).maybeSingle()).data}
 if(!person?.email)return{sent:false,reason:"No email address"};
 const seatIds=(tickets??[]).map((x:any)=>x.seat_id),{data:seats}=seatIds.length?await admin.from("seats").select("id,code,label,seat_type,section").in("id",seatIds):{data:[] as any[]};const sm=new Map((seats??[]).map((x:any)=>[x.id,x]));
 const appUrl=process.env.NEXT_PUBLIC_APP_URL||"http://localhost:3000",ticketUrl=`${appUrl}/dashboard/tickets`,gps=directions(event),d=new Date(event.ceremony_date),date=new Intl.DateTimeFormat("en-GB",{dateStyle:"long",timeZone:"Asia/Bahrain"}).format(d),time=new Intl.DateTimeFormat("en-GB",{timeStyle:"short",timeZone:"Asia/Bahrain"}).format(d);
 const attachments:EmailAttachment[]=[];const ticketRows:string[]=[];const labels:string[]=[];
 for(let i=0;i<(tickets??[]).length;i++){const t:any=(tickets??[])[i],seat:any=sm.get(t.seat_id),title=ticketTypeLabel(seat?.seat_type),seatNo=seat?.label||seat?.code||"-";labels.push(title);const card=await buildTicketCardPng({person,ticket:t,seat,event,organizationName:(org as any)?.name});attachments.push({name:`${String(person.reference_number||person.id)}-${String(seat?.seat_type||"ticket")}-${seatNo}.png`,contentType:"image/png",contentBytes:card.toString("base64")});ticketRows.push(`<tr><td style="padding:10px;border:1px solid #e5e7eb">${escapeHtml(title)}</td><td style="padding:10px;border:1px solid #e5e7eb"><strong>${escapeHtml(seatNo)}</strong></td></tr>`)}
 const subject=`${labels.length===1?labels[0]:"Your Tickets"} - ${event.name}`;
 const html=`<div style="font-family:Arial,sans-serif;line-height:1.7;color:#172033;max-width:760px;margin:auto"><h2 style="color:#101724">${escapeHtml(subject)}</h2><p>Dear Student <strong>${escapeHtml(person.full_name)}</strong>,</p><p>Your event booking and ticket issuance are confirmed.</p><p>🎫 Your ticket card image${attachments.length>1?"s are":" is"} attached.</p><table style="border-collapse:collapse;width:100%;max-width:620px"><tr><td style="padding:8px 12px"><strong>🪪 ID:</strong></td><td style="padding:8px 12px">${escapeHtml(person.reference_number||"-")}</td></tr><tr><td style="padding:8px 12px"><strong>📅 Date:</strong></td><td style="padding:8px 12px">${escapeHtml(date)}</td></tr><tr><td style="padding:8px 12px"><strong>🕒 Time:</strong></td><td style="padding:8px 12px">${escapeHtml(time)}</td></tr><tr><td style="padding:8px 12px"><strong>📍 Venue:</strong></td><td style="padding:8px 12px">${escapeHtml(event.venue||"-")}</td></tr><tr><td style="padding:8px 12px"><strong>💳 Total paid:</strong></td><td style="padding:8px 12px">BHD ${Number(booking.total_bhd||0).toFixed(3)}</td></tr></table><p><a href="${escapeHtml(gps)}"><strong>Open GPS navigation</strong></a><br/><a href="${escapeHtml(ticketUrl)}"><strong>Login to view full tickets, seats, ceremony services and other details</strong></a></p><h3 style="color:#101724">Your tickets</h3><table style="border-collapse:collapse;width:100%;max-width:620px"><thead><tr><th style="padding:10px;border:1px solid #e5e7eb;text-align:left">Ticket Type</th><th style="padding:10px;border:1px solid #e5e7eb;text-align:left">Seat</th></tr></thead><tbody>${ticketRows.join("")}</tbody></table><p><strong>The QR code is valid for one successful entry scan only.</strong></p><p>Congratulations for your graduation ✨️🎓</p><p>Kingdom University.<br/>Kind regards.</p></div>`;
 await sendGraphEmail({to:person.email,subject,html,attachments});
 await admin.from("bookings").update({confirmation_email_sent_at:new Date().toISOString()}).eq("id",booking.id);return{sent:true};
}
