import sharp from "sharp";
import {replacePlaceholders} from "./message-templates";
const esc=(v:unknown)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&apos;",'"':"&quot;"}[c]||c));
async function imageData(url?:string|null){if(!url)return"";try{const r=await fetch(url,{cache:"no-store"});if(!r.ok)return"";const b=Buffer.from(await r.arrayBuffer()),type=r.headers.get("content-type")||"image/png";return`data:${type};base64,${b.toString("base64")}`}catch{return""}}
function wrap(text:string,max=68){const lines:string[]=[];for(const para of text.split(/\n/)){let line="";for(const word of para.split(/\s+/)){if(!word)continue;if((line+" "+word).trim().length>max){if(line)lines.push(line);line=word}else line=(line+" "+word).trim()}lines.push(line)}return lines.filter((x,i,a)=>x||i<a.length-1)}
export async function createInvitationPng(design:any,values:Record<string,string>){
 const width=Number(design?.card_width||1200),height=Number(design?.card_height||675),bg=await imageData(design?.background_image_url),logo=await imageData(design?.logo_url);
 const title=replacePlaceholders(design?.title_text||"Graduation Ceremony",values),body=replacePlaceholders(design?.body_text||"Dear {{name}}, you are invited to celebrate your graduation.",values),footer=replacePlaceholders(design?.footer_text||"",values);
 const bodyLines=wrap(body,76),bodyStart=275,bodyGap=Number(design?.body_font_size||18)*1.5;
 const fields=[design?.show_name&&["Name",values.name],design?.show_reference&&["ID",values.id],design?.show_college&&["College",values.college],design?.show_degree&&["Degree",values.degree],design?.show_program&&["Program",values.program],design?.show_date&&["Date",values.date],design?.show_time&&["Time",values.time],design?.show_venue&&["Venue",values.venue],design?.show_location&&["Location",values.location]].filter(Boolean) as string[][];
 const fieldY=Math.min(bodyStart+bodyLines.length*bodyGap+42,475),fieldWidth=180,gap=12,total=Math.min(fields.length,5)*fieldWidth+(Math.min(fields.length,5)-1)*gap,start=(width-total)/2;
 const fieldSvg=fields.slice(0,5).map(([l,v],i)=>`<g transform="translate(${start+i*(fieldWidth+gap)},${fieldY})"><rect width="${fieldWidth}" height="72" rx="10" fill="#000" fill-opacity=".22" stroke="#fff" stroke-opacity=".28"/><text x="${fieldWidth/2}" y="24" text-anchor="middle" fill="${esc(design?.text_color||"#fff")}" fill-opacity=".72" font-size="11" font-family="Arial">${esc(l.toUpperCase())}</text><text x="${fieldWidth/2}" y="50" text-anchor="middle" fill="${esc(design?.text_color||"#fff")}" font-size="15" font-weight="700" font-family="${esc(design?.font_family||"Georgia")}">${esc(String(v).slice(0,28))}</text></g>`).join("");
 const svg=`<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">${bg?`<image href="${bg}" width="${width}" height="${height}" preserveAspectRatio="xMidYMid slice"/>`:`<rect width="100%" height="100%" fill="${esc(design?.background_color||"#11213A")}"/>`}<rect width="100%" height="100%" fill="#000" fill-opacity=".28"/>${logo?`<image href="${logo}" x="${width/2-75}" y="42" width="150" height="90" preserveAspectRatio="xMidYMid meet"/>`:""}<text x="50%" y="165" text-anchor="middle" fill="${esc(design?.text_color||"#fff")}" font-size="14" font-weight="700" letter-spacing="4" font-family="Arial">YOU ARE CORDIALLY INVITED</text><text x="50%" y="225" text-anchor="middle" fill="${esc(design?.accent_color||"#D4A843")}" font-size="${Number(design?.title_font_size||42)}" font-weight="700" font-family="${esc(design?.font_family||"Georgia")}">${esc(title)}</text><text x="50%" y="${bodyStart}" text-anchor="middle" fill="${esc(design?.text_color||"#fff")}" font-size="${Number(design?.body_font_size||18)}" font-family="${esc(design?.font_family||"Georgia")}">${bodyLines.map((line,i)=>`<tspan x="50%" dy="${i===0?0:bodyGap}">${esc(line)}</tspan>`).join("")}</text>${fieldSvg}<text x="50%" y="${height-42}" text-anchor="middle" fill="${esc(design?.text_color||"#fff")}" font-size="14" font-family="Arial">${esc(footer)}</text></svg>`;
 return sharp(Buffer.from(svg)).png().toBuffer();
}
