import QRCode from "qrcode";
import sharp from "sharp";
import {encodeTicketQr} from "@/lib/ticket-payload";

const esc=(v:any)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const typeLabel=(v?:string)=>v==="graduate"?"Graduate Seat":v==="staff"?"Academic Staff Seat":v==="free_guest"?"Free Guest Ticket":v==="paid_guest"?"Paid Guest Ticket":"Event Ticket";
const fmt=(v?:string)=>v?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Bahrain"}).format(new Date(v)):"-";

export async function buildTicketCardPng({person,ticket,seat,event,organizationName}:{person:any;ticket:any;seat:any;event:any;organizationName?:string}){
 const title=typeLabel(seat?.seat_type),seatNo=seat?.label||seat?.code||"Unassigned";
 const qr=await QRCode.toBuffer(encodeTicketQr({token:String(ticket?.qr_token||"")}),{type:"png",width:512,margin:8,errorCorrectionLevel:"M",color:{dark:"#101724",light:"#ffffff"}});
 const svg=Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="1580"><rect width="900" height="1580" rx="40" fill="#fffdf8"/><rect x="18" y="18" width="864" height="1544" rx="34" fill="none" stroke="#d4a843" stroke-width="6"/><rect x="42" y="42" width="816" height="170" rx="24" fill="#101724"/><text x="450" y="92" text-anchor="middle" fill="#d4a843" font-family="Arial" font-size="32" font-weight="700">${esc(organizationName||"KINGDOM UNIVERSITY")}</text><text x="450" y="154" text-anchor="middle" fill="white" font-family="Arial" font-size="28">${esc(event?.name||"GRADUATION CEREMONY")}</text><circle cx="450" cy="300" r="74" fill="#eef2f7"/><text x="450" y="316" text-anchor="middle" fill="#101724" font-family="Arial" font-size="38" font-weight="700">${esc(String(person?.full_name||"G").split(/\s+/).slice(0,2).map((x:string)=>x[0]).join("").toUpperCase())}</text><text x="450" y="420" text-anchor="middle" fill="#111827" font-family="Arial" font-size="46" font-weight="700">${esc(person?.full_name)}</text><text x="450" y="470" text-anchor="middle" fill="#475569" font-family="Arial" font-size="28">ID: ${esc(person?.reference_number||"-")}</text><rect x="210" y="515" width="480" height="74" rx="20" fill="#efe3bd"/><text x="450" y="562" text-anchor="middle" fill="#101724" font-family="Arial" font-size="31" font-weight="700">${esc(title.toUpperCase())}</text><text x="100" y="675" fill="#64748b" font-family="Arial" font-size="24">SEAT NUMBER</text><text x="100" y="735" fill="#101724" font-family="Arial" font-size="50" font-weight="700">${esc(seatNo)}</text><text x="100" y="820" fill="#64748b" font-family="Arial" font-size="24">DATE &amp; TIME</text><text x="100" y="865" fill="#101724" font-family="Arial" font-size="28">${esc(fmt(event?.ceremony_date))}</text><text x="100" y="930" fill="#64748b" font-family="Arial" font-size="24">VENUE</text><text x="100" y="975" fill="#101724" font-family="Arial" font-size="28">${esc(event?.venue||event?.venue_address||"Kingdom University")}</text><rect x="220" y="1015" width="460" height="460" rx="20" fill="#ffffff" stroke="#d4a843" stroke-width="3"/><line x1="100" y1="1505" x2="800" y2="1505" stroke="#e5e7eb" stroke-width="2"/><text x="450" y="1540" text-anchor="middle" fill="#64748b" font-family="Arial" font-size="19">Present this ticket at the entrance - QR valid for one successful scan</text></svg>`);
 const qrSized=await sharp(qr).resize(400,400,{fit:"contain",background:"#ffffff"}).png().toBuffer();
 const composites:any[]=[{input:qrSized,left:250,top:1045}];
 if(person?.photo_url){try{const response=await fetch(person.photo_url);if(response.ok){const photo=Buffer.from(await response.arrayBuffer());const portrait=await sharp(photo).resize(148,148,{fit:"cover"}).composite([{input:Buffer.from(`<svg width="148" height="148"><circle cx="74" cy="74" r="74" fill="white"/></svg>`),blend:"dest-in"}]).png().toBuffer();composites.push({input:portrait,left:376,top:226})}}catch{}}
 return sharp(svg).composite(composites).png().toBuffer();
}
export {typeLabel as ticketTypeLabel};
