import {requireProfile} from "@/lib/auth";
import {createClient} from "@/lib/supabase/server";
import {createOrganization,updateOrganization,deleteOrganization} from "../actions";
import {Building2,Pencil,Trash2} from "lucide-react";
import {AddPanel} from "@/components/AddPanel";

export default async function Page(){
 await requireProfile(["admin"]);const s=await createClient();const q=await s.from("organizations").select("*").order("name");const data:any[]=q.data??[];
 return <>
  <div className="page-head"><div><span className="eyebrow">MULTI-TENANT CONTROL</span><h1>Organizations</h1><p>Create, edit and manage independent organization workspaces.</p></div><AddPanel buttonLabel="Add organization" title="Create organization" description="Create an independent tenant workspace."><form action={createOrganization} className="form-grid cols-3 top-gap"><label>Name<input name="name" required/></label><label>Slug<input name="slug" required/></label><label>Type<select name="organization_type"><option>university</option><option>college</option><option>government</option><option>corporate</option></select></label><label>Primary color<input type="color" name="primary_color" defaultValue="#D4A843"/></label><label>Secondary color<input type="color" name="secondary_color" defaultValue="#173B62"/></label><label>Email<input type="email" name="contact_email"/></label><button className="btn btn-primary span-3">Create organization</button></form></AddPanel></div>
  <div className="grid grid-3">{data.map(o=><details className="card tenant-card" key={o.id}><summary><div className="tenant-logo" style={{background:o.primary_color}}>{o.logo_url?<img src={o.logo_url} alt=""/>:<Building2/>}</div><div><h3>{o.name}</h3><p>{o.slug}</p></div><span className="badge">{o.active?"Active":"Inactive"}</span></summary><div className="detail-list"><span>Type <b>{o.organization_type}</b></span><span>Email <b>{o.contact_email||"—"}</b></span><span>Phone <b>{o.contact_phone||"—"}</b></span><span>Timezone <b>{o.timezone||"—"}</b></span></div><form action={updateOrganization} className="form-grid cols-2"><input type="hidden" name="id" value={o.id}/><label>Name<input name="name" defaultValue={o.name}/></label><label>Slug<input name="slug" defaultValue={o.slug}/></label><label>Type<input name="organization_type" defaultValue={o.organization_type}/></label><label>Email<input name="contact_email" defaultValue={o.contact_email||""}/></label><label>Phone<input name="contact_phone" defaultValue={o.contact_phone||""}/></label><label className="check"><input type="checkbox" name="active" defaultChecked={o.active}/>Active</label><div className="actions span-2"><button className="btn btn-primary"><Pencil size={15}/>Save</button></div></form><form action={deleteOrganization}><input type="hidden" name="id" value={o.id}/><button className="btn btn-danger"><Trash2 size={15}/>Delete</button></form></details>)}</div>
 </>;
}
