"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {requireProfile} from "@/lib/auth";
import type {AppRole} from "@/lib/types";
import {fromBahrainInput} from "@/lib/event-time";

const text=(v:FormDataEntryValue|null)=>{if(typeof v!=="string")return null;const x=v.trim();return !x||x==="null"||x==="undefined"?null:x};
const uuid=(v:FormDataEntryValue|null)=>{const x=text(v);return x&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x)?x:null};
const num=(v:FormDataEntryValue|null)=>v&&String(v).trim()!==""?Number(v):null;
const aisles=(v:FormDataEntryValue|null)=>String(v||"").split(",").map(x=>Number(x.trim())).filter(x=>Number.isInteger(x)&&x>0);
function done(path:string,message:string){revalidatePath(path);redirect(`${path}?success=${encodeURIComponent(message)}`)}
function fail(path:string,message:string):never{redirect(`${path}?error=${encodeURIComponent(message)}`)}
async function mutation(table:string,action:"insert"|"update"|"delete",payload:any,id:string|undefined,path:string,message:string,roles:AppRole[]=["admin"]){
 const p=await requireProfile(roles);const s=await createClient();let q:any;
 if(action==="insert")q=s.from(table).insert({...payload,organization_id:p.organization_id});
 else if(action==="update")q=s.from(table).update(payload).eq("id",id).eq("organization_id",p.organization_id);
 else q=s.from(table).delete().eq("id",id).eq("organization_id",p.organization_id);
 const {error}=await q;if(error)fail(path,error.message);done(path,message)
}

export async function setUserPassword(fd:FormData){
 const p=await requireProfile(["admin"]);const profileId=uuid(fd.get("profile_id"));const password=String(fd.get("password")||"");
 if(!profileId)fail("/dashboard/people","Select a valid login user");if(password.length<8)fail("/dashboard/people","Password must be at least 8 characters");
 const admin=createAdminClient();const {data:owned}=await admin.from("profiles").select("id").eq("id",profileId).eq("organization_id",p.organization_id).single();if(!owned)fail("/dashboard/people","User is not part of your organization");
 const {error}=await admin.auth.admin.updateUserById(profileId,{password});if(error)fail("/dashboard/people",error.message);done("/dashboard/people","Password changed successfully")
}

export async function sendPasswordReset(fd:FormData){
 const p=await requireProfile(["admin"]);const email=String(fd.get("email")||"").trim().toLowerCase();if(!email)fail("/dashboard/people","User email is missing");const s=await createClient();const origin=process.env.NEXT_PUBLIC_APP_URL||"";const {error}=await s.auth.resetPasswordForEmail(email,{redirectTo:`${origin}/login?reset=1`});if(error)fail("/dashboard/people",error.message);done("/dashboard/people","Password reset email sent successfully")
}

export async function saveOrganization(fd:FormData){const p=await requireProfile(["admin"]);const s=createAdminClient();const id=text(fd.get("id"))||p.organization_id;const {error}=await s.from("organizations").update({name:text(fd.get("name")),slug:text(fd.get("slug")),organization_type:text(fd.get("organization_type")),primary_color:text(fd.get("primary_color")),secondary_color:text(fd.get("secondary_color")),background_color:text(fd.get("background_color")),surface_color:text(fd.get("surface_color")),accent_color:text(fd.get("accent_color")),logo_url:text(fd.get("logo_url")),domain:text(fd.get("domain")),timezone:text(fd.get("timezone")),locale:text(fd.get("locale")),contact_email:text(fd.get("contact_email")),contact_phone:text(fd.get("contact_phone")),address:text(fd.get("address")),contact_title:text(fd.get("contact_title")),contact_description:text(fd.get("contact_description")),contact_whatsapp:text(fd.get("contact_whatsapp")),tailor_name:text(fd.get("tailor_name")),tailor_phone:text(fd.get("tailor_phone")),tailor_email:text(fd.get("tailor_email")),photographer_name:text(fd.get("photographer_name")),photographer_phone:text(fd.get("photographer_phone")),photographer_email:text(fd.get("photographer_email")),active:fd.get("active")==="on"}).eq("id",id).select("id").single();if(error)fail("/dashboard/settings",error.message);done("/dashboard/settings","Organization identity, contact and branding settings saved successfully")}
export async function createOrganization(fd:FormData){await requireProfile(["admin"]);const s=createAdminClient();const {error}=await s.from("organizations").insert({name:String(fd.get("name")),slug:String(fd.get("slug")),organization_type:String(fd.get("organization_type")||"university"),primary_color:String(fd.get("primary_color")||"#D4A843"),secondary_color:String(fd.get("secondary_color")||"#173B62"),contact_email:text(fd.get("contact_email")),active:true});if(error)fail("/dashboard/organizations",error.message);done("/dashboard/organizations","Organization created successfully")}
export async function updateOrganization(fd:FormData){await mutation("organizations","update",{name:String(fd.get("name")),slug:String(fd.get("slug")),organization_type:String(fd.get("organization_type")||"university"),contact_email:text(fd.get("contact_email")),contact_phone:text(fd.get("contact_phone")),active:fd.get("active")==="on"},String(fd.get("id")),"/dashboard/organizations","Organization updated successfully")}
export async function deleteOrganization(fd:FormData){const p=await requireProfile(["admin"]);const id=String(fd.get("id"));if(id===p.organization_id)fail("/dashboard/organizations","You cannot delete the organization you are currently using");const s=createAdminClient();const {error}=await s.from("organizations").delete().eq("id",id);if(error)fail("/dashboard/organizations",error.message);done("/dashboard/organizations","Organization deleted successfully")}
const eventPayload=(fd:FormData)=>({organization_id:String(fd.get("organization_id")||""),name:String(fd.get("name")),short_name:text(fd.get("short_name")),event_type:String(fd.get("event_type")||"graduation"),description:text(fd.get("description")),ceremony_date:fromBahrainInput(fd.get("ceremony_date")),end_date:fromBahrainInput(fd.get("end_date")),venue:String(fd.get("venue")),venue_address:text(fd.get("venue_address")),latitude:num(fd.get("latitude")),longitude:num(fd.get("longitude")),map_url:text(fd.get("map_url")),registration_open_at:text(fd.get("registration_open_at")),registration_close_at:text(fd.get("registration_close_at")),booking_deadline:text(fd.get("booking_deadline")),status:String(fd.get("status")||"draft"),free_ticket_quota:Number(fd.get("free_ticket_quota")||2),paid_ticket_quota:Number(fd.get("paid_ticket_quota")||2),paid_hold_minutes:Number(fd.get("paid_hold_minutes")||15),allow_guest_booking:fd.get("allow_guest_booking")==="on",allow_paid_booking:fd.get("allow_paid_booking")==="on",max_guest_tickets:Number(fd.get("max_guest_tickets")||4),currency:String(fd.get("currency")||"BHD"),invitation_title:text(fd.get("invitation_title")),invitation_message:text(fd.get("invitation_message")),ticket_footer:text(fd.get("ticket_footer")),paid_booking_open_at:text(fd.get("paid_booking_open_at")),paid_booking_close_at:text(fd.get("paid_booking_close_at")),extra_ticket_open_at:text(fd.get("extra_ticket_open_at")),extra_ticket_close_at:text(fd.get("extra_ticket_close_at")),paid_ticket_price_bhd:Number(fd.get("paid_ticket_price_bhd")||0),extra_ticket_price_bhd:Number(fd.get("extra_ticket_price_bhd")||0),registration_fee_bhd:Number(fd.get("registration_fee_bhd")||180),live_stream_url:text(fd.get("live_stream_url")),live_stream_enabled:fd.get("live_stream_enabled")==="on",show_invitation_to_students:fd.get("show_invitation_to_students")==="on",student_seat_access_mode:String(fd.get("student_seat_access_mode")||"book")});
export async function createEvent(fd:FormData){const p=await requireProfile(["admin"]);const s=await createClient();const payload=eventPayload(fd);payload.organization_id=payload.organization_id||p.organization_id;const {error}=await s.from("events").insert({...payload,created_by:p.id});if(error)fail("/dashboard/events",error.message);done("/dashboard/events","Event created successfully")}
export async function updateEvent(fd:FormData){const p=await requireProfile(["admin"]);const s=await createClient();const payload=eventPayload(fd);delete (payload as any).organization_id;const {error}=await s.from("events").update(payload).eq("id",String(fd.get("id"))).eq("organization_id",p.organization_id);if(error)fail("/dashboard/events",error.message);done("/dashboard/events","Event saved successfully")}
export async function deleteEvent(fd:FormData){await mutation("events","delete",{},String(fd.get("id")),"/dashboard/events","Event deleted successfully")}
export async function createPerson(fd:FormData){
 const p=await requireProfile(["admin"]);const admin=createAdminClient();const email=String(fd.get("email")||"").trim().toLowerCase();const personType=String(fd.get("person_type")||"guest");const role=(personType==="vip"?"vip":String(fd.get("role")||"student")) as AppRole;const extra=personType==="vip"?[]:String(fd.get("additional_roles")||"").split(/[|;]/).map(x=>x.trim()).filter(Boolean) as AppRole[];const valid=["student","admin","scanner","regcom","vip","land","finance","tailor","photographer","academic_staff"];
 if(!valid.includes(role)||extra.some(x=>!valid.includes(x)))fail("/dashboard/people","Invalid role value");let reference=text(fd.get("reference_number"));if(personType==="student"&&!reference)fail("/dashboard/people","Student ID is required");if(!reference)reference=`USR-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
 if(email){const {data:duplicate}=await admin.from("people_directory").select("id,full_name").eq("organization_id",p.organization_id).ilike("email",email).maybeSingle();if(duplicate)fail("/dashboard/people",`This email is already assigned to ${duplicate.full_name}.`)}
 let profileId:string|null=null;if(fd.get("create_login")==="on"){
  const password=String(fd.get("password")||"");if(personType==="vip")fail("/dashboard/people","Invited VIPs do not require login accounts");if(!email)fail("/dashboard/people","Email is required to create a login");if(password.length<8)fail("/dashboard/people","Password must be at least 8 characters");
  const created=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:String(fd.get("full_name"))}});if(created.error){const listed=await admin.auth.admin.listUsers({page:1,perPage:1000});const existing=(listed.data?.users as any[]|undefined)?.find((u:any)=>String(u.email||"").toLowerCase()===email);if(!existing)fail("/dashboard/people",created.error.message);profileId=existing.id}else profileId=created.data.user.id;
  const {data:existingProfile}=await admin.from("profiles").select("organization_id").eq("id",profileId).maybeSingle();if(existingProfile&&existingProfile.organization_id!==p.organization_id)fail("/dashboard/people","This email belongs to another organization account");
  const {error:pe}=await admin.from("profiles").upsert({id:profileId,organization_id:p.organization_id,email,full_name:String(fd.get("full_name")),role,person_type:personType,reference_number:reference,phone:text(fd.get("phone")),active:true});if(pe)fail("/dashboard/people",pe.message);const roles=[role,...extra.filter(x=>x!==role)];await admin.from("profile_roles").delete().eq("profile_id",profileId);const {error:re}=await admin.from("profile_roles").insert(roles.map(x=>({organization_id:p.organization_id,profile_id:profileId,role:x})));if(re)fail("/dashboard/people",re.message)
 }
 const isStudent=personType==="student",isAcademic=personType==="academic_staff";const {error}=await admin.from("people_directory").insert({organization_id:p.organization_id,profile_id:profileId,email:email||null,full_name:String(fd.get("full_name")),person_type:personType,role,reference_number:reference,college_id:(isStudent||isAcademic)?uuid(fd.get("college_id")):null,degree_level_id:isStudent?uuid(fd.get("degree_level_id")):null,program_id:isStudent?uuid(fd.get("program_id")):null,phone:text(fd.get("phone")),gender:text(fd.get("gender")),active:true});if(error)fail("/dashboard/people",error.message);done("/dashboard/people",personType==="vip"?"VIP invited person added successfully":"User created successfully")
}
export async function updatePerson(fd:FormData){const p=await requireProfile(["admin"]);const admin=createAdminClient();const id=uuid(fd.get("id"));if(!id)fail("/dashboard/people","Invalid user");const personType=String(fd.get("person_type")||"guest"),role=String(fd.get("role")||"student") as AppRole;const isStudent=personType==="student",isAcademic=personType==="academic_staff";let photoUrl=text(fd.get("existing_photo_url"));const photo=fd.get("photo");if(p.role==="admin"&&photo instanceof File&&photo.size>0){if(!photo.type.startsWith("image/"))fail("/dashboard/people","Profile photo must be an image");if(photo.size>5*1024*1024)fail("/dashboard/people","Profile photo must be smaller than 5 MB");await admin.storage.createBucket("profile-photos",{public:true}).catch(()=>{});const ext=(photo.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"");const path=`${p.organization_id}/${id}.${ext}`;const uploaded=await admin.storage.from("profile-photos").upload(path,Buffer.from(await photo.arrayBuffer()),{contentType:photo.type,upsert:true});if(uploaded.error)fail("/dashboard/people",uploaded.error.message);photoUrl=admin.storage.from("profile-photos").getPublicUrl(path).data.publicUrl}const {data:person,error:pe}=await admin.from("people_directory").update({full_name:String(fd.get("full_name")),email:text(fd.get("email")),person_type:personType,role,reference_number:text(fd.get("reference_number")),college_id:(isStudent||isAcademic)?uuid(fd.get("college_id")):null,degree_level_id:isStudent?uuid(fd.get("degree_level_id")):null,program_id:isStudent?uuid(fd.get("program_id")):null,phone:text(fd.get("phone")),gender:text(fd.get("gender")),active:fd.get("active")==="on",photo_url:photoUrl}).eq("id",id).eq("organization_id",p.organization_id).select("profile_id").single();if(pe)fail("/dashboard/people",pe.message);if(person?.profile_id){const extra=String(fd.get("additional_roles")||"").split(/[|;]/).map(x=>x.trim()).filter(Boolean) as AppRole[];await admin.from("profiles").update({full_name:String(fd.get("full_name")),email:text(fd.get("email")),role,person_type:personType,reference_number:text(fd.get("reference_number")),phone:text(fd.get("phone")),photo_url:photoUrl}).eq("id",person.profile_id);await admin.from("profile_roles").delete().eq("profile_id",person.profile_id);const roles=[role,...extra.filter(x=>x!==role)];const {error:re}=await admin.from("profile_roles").insert(roles.map(x=>({organization_id:p.organization_id,profile_id:person.profile_id,role:x})));if(re)fail("/dashboard/people",re.message)}done("/dashboard/people","User updated successfully")}
export async function deletePerson(fd:FormData){
 const p=await requireProfile(["admin"]);const admin=createAdminClient();const id=uuid(fd.get("id"));if(!id)fail("/dashboard/people","Invalid directory user");
 const {data:row}=await admin.from("people_directory").select("profile_id").eq("id",id).eq("organization_id",p.organization_id).maybeSingle();
 const {error}=await admin.from("people_directory").delete().eq("id",id).eq("organization_id",p.organization_id);if(error)fail("/dashboard/people",error.message);
 if(row?.profile_id){await admin.from("profile_roles").delete().eq("profile_id",row.profile_id).eq("organization_id",p.organization_id);await admin.from("profiles").delete().eq("id",row.profile_id).eq("organization_id",p.organization_id);await admin.auth.admin.deleteUser(row.profile_id)}
 done("/dashboard/people","User deleted successfully")
}
export async function deleteSystemUser(fd:FormData){
 const p=await requireProfile(["admin"]);const admin=createAdminClient();const profileId=uuid(fd.get("profile_id")||fd.get("id"));if(!profileId)fail("/dashboard/people","Invalid system user");
 const {data:owned}=await admin.from("profiles").select("id,role").eq("id",profileId).eq("organization_id",p.organization_id).maybeSingle();if(!owned)fail("/dashboard/people","System user not found");if(profileId===p.id)fail("/dashboard/people","You cannot delete your own account");
 await admin.from("people_directory").delete().eq("profile_id",profileId).eq("organization_id",p.organization_id);await admin.from("profile_roles").delete().eq("profile_id",profileId).eq("organization_id",p.organization_id);await admin.from("profiles").delete().eq("id",profileId).eq("organization_id",p.organization_id);const {error}=await admin.auth.admin.deleteUser(profileId);if(error)fail("/dashboard/people",error.message);done("/dashboard/people","System user deleted successfully")
}
export async function createCollege(fd:FormData){await mutation("colleges","insert",{name:String(fd.get("name")),code:String(fd.get("code")),color:String(fd.get("color")||"#4A90D9"),display_order:Number(fd.get("display_order")||0),active:true},undefined,"/dashboard/settings","College created successfully")}
export async function updateCollege(fd:FormData){await mutation("colleges","update",{name:String(fd.get("name")),code:String(fd.get("code")),color:String(fd.get("color")||"#4A90D9"),display_order:Number(fd.get("display_order")||0),active:fd.get("active")==="on"},String(fd.get("id")),"/dashboard/settings","College updated successfully")}
export async function deleteCollege(fd:FormData){await mutation("colleges","delete",{},String(fd.get("id")),"/dashboard/settings","College deleted successfully")}
export async function createDegree(fd:FormData){await mutation("degree_levels","insert",{name:String(fd.get("name")),code:String(fd.get("code")),display_order:Number(fd.get("display_order")||0),active:true},undefined,"/dashboard/settings","Degree created successfully")}
export async function updateDegree(fd:FormData){await mutation("degree_levels","update",{name:String(fd.get("name")),code:String(fd.get("code")),display_order:Number(fd.get("display_order")||0),active:fd.get("active")==="on"},String(fd.get("id")),"/dashboard/settings","Degree updated successfully")}
export async function deleteDegree(fd:FormData){await mutation("degree_levels","delete",{},String(fd.get("id")),"/dashboard/settings","Degree deleted successfully")}
export async function createProgram(fd:FormData){await mutation("academic_programs","insert",{name:String(fd.get("name")),code:String(fd.get("code")),college_id:String(fd.get("college_id")),degree_level_id:String(fd.get("degree_level_id")),display_order:Number(fd.get("display_order")||0),active:true},undefined,"/dashboard/settings","Program created successfully")}
export async function updateProgram(fd:FormData){await mutation("academic_programs","update",{name:String(fd.get("name")),code:String(fd.get("code")),college_id:String(fd.get("college_id")),degree_level_id:String(fd.get("degree_level_id")),display_order:Number(fd.get("display_order")||0),active:fd.get("active")==="on"},String(fd.get("id")),"/dashboard/settings","Program updated successfully")}
export async function deleteProgram(fd:FormData){await mutation("academic_programs","delete",{},String(fd.get("id")),"/dashboard/settings","Program deleted successfully")}
async function saveZone(fd:FormData,id?:string){
 const p=await requireProfile(["admin","land"]);const s=await createClient();
 const eventId=uuid(fd.get("event_id"));const zoneId=id?uuid(id):null;
 if(!eventId)fail("/dashboard/seats","Please select a valid event");
 if(id&&!zoneId)fail("/dashboard/seats","Invalid seating zone ID");
 const payload={organization_id:p.organization_id,event_id:eventId,name:String(fd.get("name")||"").trim(),zone_type:String(fd.get("zone_type")||"free_guest"),rows_count:Number(fd.get("rows_count")||0),columns_count:Number(fd.get("columns_count")||0),color:String(fd.get("color")||"#D4A843"),price_bhd:Number(fd.get("price_bhd")||0),display_order:Number(fd.get("display_order")||0),college_id:uuid(fd.get("college_id")),seat_prefix:String(fd.get("seat_prefix")||"S").trim(),aisle_columns:aisles(fd.get("aisle_columns")),stage_side:String(fd.get("stage_side")||"center")};
 if(!payload.name||payload.rows_count<1||payload.columns_count<1)fail("/dashboard/seats","Zone name, rows and columns are required");
 const result=zoneId?await s.from("seating_zones").update(payload).eq("id",zoneId).eq("organization_id",p.organization_id).select("id").single():await s.from("seating_zones").insert(payload).select("id").single();
 if(result.error)fail("/dashboard/seats",result.error.message);const savedId=zoneId||result.data?.id;if(!savedId)fail("/dashboard/seats","Zone was saved but no ID was returned");
 const {error}=await s.rpc("generate_zone_seats",{p_zone_id:savedId});if(error)fail("/dashboard/seats",error.message);done("/dashboard/seats",zoneId?"Seating zone updated and regenerated successfully":"Seating zone created successfully")
}
export async function createZone(fd:FormData){return saveZone(fd)}export async function updateZone(fd:FormData){return saveZone(fd,text(fd.get("id"))||undefined)}
export async function regenerateZone(fd:FormData){const s=await createClient();await requireProfile(["admin","land"]);const zoneId=String(fd.get("id"));const {error}=await s.rpc("generate_zone_seats",{p_zone_id:zoneId});if(error)fail("/dashboard/seats",error.message);const{data:z}=await s.from("seating_zones").select("event_id").eq("id",zoneId).single();if(z?.event_id)await s.rpc("reconcile_event_seat_statuses",{p_event_id:z.event_id});done("/dashboard/seats","Seats regenerated and stale status corrected")}
export async function deleteZone(fd:FormData){await mutation("seating_zones","delete",{},String(fd.get("id")),"/dashboard/seats","Seating zone deleted successfully",["admin","land"])}
export async function updateFitting(fd:FormData){const p=await requireProfile(["admin","regcom","tailor"]);const s=await createClient();const {error}=await s.from("fittings").upsert({organization_id:p.organization_id,event_id:String(fd.get("event_id")),person_id:String(fd.get("person_id")),gown_size:text(fd.get("gown_size")),status:String(fd.get("status")||"pending"),collected_status:String(fd.get("collected_status")||"pending"),notes:text(fd.get("notes")),updated_by:p.id,updated_at:new Date().toISOString()},{onConflict:"event_id,person_id"});if(error)fail("/dashboard/fitting",error.message);done("/dashboard/fitting","Fitting record saved successfully")}
export async function updatePhoto(fd:FormData){const p=await requireProfile(["admin","regcom","photographer"]);const s=await createClient();const {error}=await s.from("photo_sessions").upsert({organization_id:p.organization_id,event_id:String(fd.get("event_id")),person_id:String(fd.get("person_id")),status:String(fd.get("status")||"pending"),photo_url:text(fd.get("photo_url")),notes:text(fd.get("notes")),updated_by:p.id,updated_at:new Date().toISOString()},{onConflict:"event_id,person_id"});if(error)fail("/dashboard/photography",error.message);done("/dashboard/photography","Photography status updated successfully")}
export async function createService(fd:FormData){await mutation("event_services","insert",{event_id:String(fd.get("event_id")),name:String(fd.get("name")),provider_name:text(fd.get("provider_name")),status:String(fd.get("status")||"planned"),contact_phone:text(fd.get("contact_phone")),contact_email:text(fd.get("contact_email")),price_bhd:Number(fd.get("price_bhd")||0),image_url:text(fd.get("image_url")),service_url:text(fd.get("service_url")),service_type:String(fd.get("service_type")||"general"),notes:text(fd.get("notes"))},undefined,"/dashboard/services","Service created successfully")}
export async function updateService(fd:FormData){await mutation("event_services","update",{event_id:String(fd.get("event_id")),name:String(fd.get("name")),provider_name:text(fd.get("provider_name")),status:String(fd.get("status")||"planned"),contact_phone:text(fd.get("contact_phone")),contact_email:text(fd.get("contact_email")),price_bhd:Number(fd.get("price_bhd")||0),image_url:text(fd.get("image_url")),service_url:text(fd.get("service_url")),service_type:String(fd.get("service_type")||"general"),notes:text(fd.get("notes"))},String(fd.get("id")),"/dashboard/services","Service updated successfully")}
export async function deleteService(fd:FormData){await mutation("event_services","delete",{},String(fd.get("id")),"/dashboard/services","Service deleted successfully")}
export async function createInvitedVip(fd:FormData){
 const p=await requireProfile(["admin","vip"]);const s=await createClient();const full_name=String(fd.get("full_name")||"").trim();if(!full_name)fail("/dashboard/vip","VIP name is required");const {error}=await s.from("people_directory").insert({organization_id:p.organization_id,full_name,email:text(fd.get("email")),phone:text(fd.get("phone")),reference_number:text(fd.get("reference_number"))||`VIP-${Date.now()}`,person_type:"vip",role:"vip",active:true});if(error)fail("/dashboard/vip",error.message);done("/dashboard/vip","Invited VIP added successfully")
}

export async function createVipAssignment(fd:FormData){
 const p=await requireProfile(["admin","vip"]);const s=await createClient();const eventId=uuid(fd.get("event_id")),personId=uuid(fd.get("person_id")),seatId=uuid(fd.get("seat_id"));if(!eventId||!personId)fail("/dashboard/vip","Select a valid event and VIP");
 if(seatId){const {data:seat,error:se}=await s.from("seats").select("id,status,section,event_id").eq("id",seatId).eq("organization_id",p.organization_id).single();if(se||!seat||seat.section!=="vip"||seat.event_id!==eventId||seat.status!=="available")fail("/dashboard/vip","The selected VIP seat is no longer available")}
 const {error}=await s.from("vip_assignments").insert({organization_id:p.organization_id,event_id:eventId,person_id:personId,seat_id:seatId,arrival_status:String(fd.get("arrival_status")||"pending"),seating_status:seatId?"seated":"pending",notes:text(fd.get("notes"))});if(error)fail("/dashboard/vip",error.message);if(seatId)await s.from("seats").update({status:"booked"}).eq("id",seatId);done("/dashboard/vip","VIP assigned successfully")
}
export async function updateVipAssignment(fd:FormData){
 const p=await requireProfile(["admin","vip"]);const s=await createClient();const id=uuid(fd.get("id")),seatId=uuid(fd.get("seat_id"));if(!id)fail("/dashboard/vip","Invalid VIP assignment");const {data:old,error:oe}=await s.from("vip_assignments").select("seat_id,event_id").eq("id",id).eq("organization_id",p.organization_id).single();if(oe)fail("/dashboard/vip",oe.message);
 if(seatId&&seatId!==old.seat_id){const {data:seat}=await s.from("seats").select("id,status,section,event_id").eq("id",seatId).single();if(!seat||seat.section!=="vip"||seat.event_id!==old.event_id||seat.status!=="available")fail("/dashboard/vip","The selected VIP seat is no longer available")}
 const {error}=await s.from("vip_assignments").update({seat_id:seatId,arrival_status:String(fd.get("arrival_status")||"pending"),seating_status:seatId?"seated":"pending",notes:text(fd.get("notes")),updated_at:new Date().toISOString()}).eq("id",id).eq("organization_id",p.organization_id);if(error)fail("/dashboard/vip",error.message);if(old.seat_id&&old.seat_id!==seatId)await s.from("seats").update({status:"available"}).eq("id",old.seat_id);if(seatId)await s.from("seats").update({status:"booked"}).eq("id",seatId);done("/dashboard/vip","VIP updated successfully")
}
export async function deleteVipAssignment(fd:FormData){const p=await requireProfile(["admin","vip"]);const s=await createClient();const id=uuid(fd.get("id"));if(!id)fail("/dashboard/vip","Invalid VIP assignment");const {data:r}=await s.from("vip_assignments").select("seat_id").eq("id",id).eq("organization_id",p.organization_id).single();const {error}=await s.from("vip_assignments").delete().eq("id",id).eq("organization_id",p.organization_id);if(error)fail("/dashboard/vip",error.message);if(r?.seat_id)await s.from("seats").update({status:"available"}).eq("id",r.seat_id);done("/dashboard/vip","VIP assignment deleted successfully")}
export async function saveInvitationDesign(fd:FormData){const p=await requireProfile(["admin","regcom"]);const s=await createClient();const payload={organization_id:p.organization_id,event_id:String(fd.get("event_id")),name:String(fd.get("name")||"Default invitation"),title_text:text(fd.get("title_text")),body_text:text(fd.get("body_text")),footer_text:text(fd.get("footer_text")),font_family:String(fd.get("font_family")||"Arial"),title_font_size:Number(fd.get("title_font_size")||34),body_font_size:Number(fd.get("body_font_size")||18),text_color:String(fd.get("text_color")||"#FFFFFF"),accent_color:String(fd.get("accent_color")||"#D4A843"),background_color:String(fd.get("background_color")||"#0C0D11"),background_image_url:text(fd.get("background_image_url")),logo_url:text(fd.get("logo_url")),show_name:fd.get("show_name")==="on",show_reference:fd.get("show_reference")==="on",show_college:fd.get("show_college")==="on",show_program:fd.get("show_program")==="on",show_degree:fd.get("show_degree")==="on",show_date:fd.get("show_date")==="on",show_time:fd.get("show_time")==="on",show_venue:fd.get("show_venue")==="on",show_location:fd.get("show_location")==="on",email_subject:text(fd.get("email_subject")),email_body:text(fd.get("email_body")),updated_at:new Date().toISOString()};const id=text(fd.get("id"));const {error}=id?await s.from("invitation_designs").update(payload).eq("id",id).eq("organization_id",p.organization_id):await s.from("invitation_designs").insert(payload);if(error)fail("/dashboard/email",error.message);done("/dashboard/email","Invitation design saved successfully")}

export async function deleteFitting(fd:FormData){await mutation("fittings","delete",{},String(fd.get("id")),"/dashboard/fitting","Fitting record deleted successfully",["admin","regcom","tailor"])}
export async function deletePhoto(fd:FormData){await mutation("photo_sessions","delete",{},String(fd.get("id")),"/dashboard/photography","Photography record deleted successfully",["admin","regcom","photographer"])}
export async function quickPersonStatus(fd:FormData){const p=await requireProfile(["admin","regcom","finance","tailor","photographer"]);const field=String(fd.get("field"));const allowed:any={registration_status:["admin","regcom"],payment_status:["admin","regcom","finance"]};if(!allowed[field]?.includes(p.role))fail("/dashboard/people","Not authorized");const s=await createClient();const value=String(fd.get("value"));const payload:any={[field]:value};const {error}=await s.from("people_directory").update(payload).eq("id",String(fd.get("id"))).eq("organization_id",p.organization_id);if(error)fail("/dashboard/people",error.message);done("/dashboard/people","Status updated successfully")}

export async function updateOperationalStatus(fd:FormData){
 const p=await requireProfile(["admin","regcom","finance","tailor","photographer","vip"]);const s=await createClient();
 const table=String(fd.get("table"));const id=uuid(fd.get("id"));const field=String(fd.get("field"));const value=String(fd.get("value"));const path=String(fd.get("return_path")||"/dashboard");
 const allowed:Record<string,string[]>={people_directory:["registration_status","payment_status","entered_status"],fittings:["status","collected_status"],photo_sessions:["status"],vip_assignments:["arrival_status","seating_status"],event_services:["status"]};
 if(!id||!allowed[table]?.includes(field))fail(path,"Invalid status update");
 const {error}=await s.from(table).update({[field]:value,updated_at:new Date().toISOString()}).eq("id",id).eq("organization_id",p.organization_id);if(error)fail(path,error.message);done(path,"Status updated successfully")
}

export async function assignSeatByAdmin(fd:FormData){
 const p=await requireProfile(["admin","regcom"]);const admin=createAdminClient();const eventId=uuid(fd.get("event_id")),personId=uuid(fd.get("person_id")),seatId=uuid(fd.get("seat_id"));const returnPath="/dashboard/bookings";if(!eventId||!personId||!seatId)fail(returnPath,"Select a student/staff member and an available seat");
 const [{data:person,error:pe},{data:seat,error:se}]=await Promise.all([admin.from("people_directory").select("id,profile_id,full_name,person_type").eq("id",personId).eq("organization_id",p.organization_id).single(),admin.from("seats").select("id,event_id,status,price_bhd,seat_type,code").eq("id",seatId).eq("organization_id",p.organization_id).single()]);if(pe||!person)fail(returnPath,pe?.message||"User not found");if(se||!seat||seat.event_id!==eventId||seat.status!=="available")fail(returnPath,"The selected seat is no longer available");
 const {data:booking,error:be}=await admin.from("bookings").insert({organization_id:p.organization_id,event_id:eventId,user_id:person.profile_id||null,person_id:person.id,status:"confirmed",total_bhd:0,assigned_by_admin:true}).select("id").single();if(be||!booking)fail(returnPath,be?.message||"Could not create booking");
 await admin.from("booking_seats").delete().eq("seat_id",seat.id);const bs=await admin.from("booking_seats").insert({booking_id:booking.id,seat_id:seat.id,price_bhd:0});if(bs.error){await admin.from("bookings").delete().eq("id",booking.id);fail(returnPath,bs.error.message)}
 const t=await admin.from("tickets").insert({organization_id:p.organization_id,event_id:eventId,user_id:person.profile_id||null,person_id:person.id,seat_id:seat.id,booking_id:booking.id,status:"valid",assigned_by_admin:true});if(t.error){await admin.from("booking_seats").delete().eq("booking_id",booking.id);await admin.from("bookings").delete().eq("id",booking.id);fail(returnPath,t.error.message)}await admin.from("seats").update({status:"booked"}).eq("id",seat.id);done(returnPath,`${seat.code} assigned without payment`)
}


export async function assignSpecificGuestSeatByAdmin(fd:FormData){
 const p=await requireProfile(["admin"]);const admin=createAdminClient();const eventId=uuid(fd.get("event_id")),personId=uuid(fd.get("person_id")),seatId=uuid(fd.get("seat_id"));const seatType=String(fd.get("seat_type"));const path="/dashboard/bookings";
 if(!eventId||!personId||!seatId||!["free_guest","paid_guest"].includes(seatType))fail(path,"Select an available guest seat");
 const [{data:seat},{data:person}]=await Promise.all([admin.from("seats").select("id,event_id,status,seat_type,code").eq("id",seatId).eq("organization_id",p.organization_id).single(),admin.from("people_directory").select("id,profile_id").eq("id",personId).eq("organization_id",p.organization_id).single()]);
 if(!seat||seat.event_id!==eventId||seat.status!=="available"||seat.seat_type!==seatType)fail(path,"The selected guest seat is no longer available");const [{data:event},{count:used}]=await Promise.all([admin.from("events").select("free_ticket_quota,paid_ticket_quota").eq("id",eventId).single(),admin.from("tickets").select("id,seats!inner(seat_type)",{count:"exact",head:true}).eq("event_id",eventId).eq("person_id",personId).eq("status","valid").eq("seats.seat_type",seatType)]);const quota=seatType==="free_guest"?Number(event?.free_ticket_quota||0):Number(event?.paid_ticket_quota||0);if(Number(used||0)>=quota)fail(path,`The configured ${seatType==="free_guest"?"free":"paid"} quota of ${quota} has already been reached`);
 const {data:booking,error:be}=await admin.from("bookings").insert({organization_id:p.organization_id,event_id:eventId,user_id:person?.profile_id||null,person_id:personId,status:"confirmed",total_bhd:0,assigned_by_admin:true}).select("id").single();if(be||!booking)fail(path,be?.message||"Could not create booking");
 await admin.from("booking_seats").delete().eq("seat_id",seat.id);const bs=await admin.from("booking_seats").insert({booking_id:booking.id,seat_id:seat.id,price_bhd:0});if(bs.error)fail(path,bs.error.message);
 const t=await admin.from("tickets").insert({organization_id:p.organization_id,event_id:eventId,user_id:person?.profile_id||null,person_id:personId,seat_id:seat.id,booking_id:booking.id,status:"valid",assigned_by_admin:true});if(t.error)fail(path,t.error.message);
 await admin.from("seats").update({status:"booked"}).eq("id",seat.id);done(path,`${seat.code} assigned successfully`)
}

export async function updateStudentPaymentStatus(fd:FormData){const p=await requireProfile(["admin","finance"]);const id=uuid(fd.get("id"));const value=String(fd.get("payment_status")||"pending");if(!id||!["pending","paid","waived","refunded"].includes(value))fail("/dashboard/finance","Invalid payment update");const s=createAdminClient();const{data,error}=await s.from("people_directory").update({payment_status:value}).eq("id",id).eq("organization_id",p.organization_id).eq("person_type","student").select("id,payment_status").single();if(error||!data)fail("/dashboard/finance",error?.message||"Student payment record was not updated");revalidatePath("/dashboard");revalidatePath("/dashboard/bookings");revalidatePath("/dashboard/reports");revalidatePath("/dashboard/people");done("/dashboard/finance",`Payment status updated to ${value}`)
}

export async function createExpense(fd:FormData){const p=await requireProfile(["admin","finance"]);const s=await createClient();const payload={organization_id:p.organization_id,event_id:uuid(fd.get("event_id")),item_name:text(fd.get("item_name")),service_details:text(fd.get("service_details")),unit_price_bhd:Number(fd.get("unit_price_bhd")||0),quantity:Number(fd.get("quantity")||1),receipt_no:text(fd.get("receipt_no")),vendor:text(fd.get("vendor")),receipt_date:text(fd.get("receipt_date")),completion_date:text(fd.get("completion_date")),status:String(fd.get("status")||"pending"),notes:text(fd.get("notes")),created_by:p.id};const{error}=await s.from("ceremony_expenses").insert(payload);if(error)fail("/dashboard/finance",error.message);done("/dashboard/finance","Expense added successfully")}
export async function updateExpense(fd:FormData){const p=await requireProfile(["admin","finance"]);const s=await createClient();const{error}=await s.from("ceremony_expenses").update({item_name:text(fd.get("item_name")),service_details:text(fd.get("service_details")),unit_price_bhd:Number(fd.get("unit_price_bhd")||0),quantity:Number(fd.get("quantity")||1),receipt_no:text(fd.get("receipt_no")),vendor:text(fd.get("vendor")),receipt_date:text(fd.get("receipt_date")),completion_date:text(fd.get("completion_date")),status:String(fd.get("status")||"pending"),notes:text(fd.get("notes")),updated_at:new Date().toISOString()}).eq("id",uuid(fd.get("id"))).eq("organization_id",p.organization_id);if(error)fail("/dashboard/finance",error.message);done("/dashboard/finance","Expense updated successfully")}
export async function deleteExpense(fd:FormData){await mutation("ceremony_expenses","delete",{},String(fd.get("id")),"/dashboard/finance","Expense deleted successfully",["admin","finance"])}
export async function createRevenueAdjustment(fd:FormData){const p=await requireProfile(["admin"]);const s=await createClient();const{error}=await s.from("revenue_adjustments").insert({organization_id:p.organization_id,event_id:uuid(fd.get("event_id")),person_id:uuid(fd.get("person_id")),amount_bhd:Number(fd.get("amount_bhd")||0),source:"manual",description:text(fd.get("description")),created_by:p.id});if(error)fail("/dashboard/finance",error.message);done("/dashboard/finance","Revenue adjustment added")}
export async function deleteRevenueAdjustment(fd:FormData){await mutation("revenue_adjustments","delete",{},String(fd.get("id")),"/dashboard/finance","Revenue adjustment deleted",["admin"])}

export async function assignGuestSeatsByAdmin(fd:FormData){
 const p=await requireProfile(["admin"]);const admin=createAdminClient();const eventId=uuid(fd.get("event_id")),personId=uuid(fd.get("person_id"));const seatType=String(fd.get("seat_type"));const count=Math.max(0,Number(fd.get("count")||0));const path="/dashboard/bookings";
 if(!eventId||!personId||!['free_guest','paid_guest'].includes(seatType))fail(path,"Invalid guest-seat request");
 const [{data:existing},{data:event}]=await Promise.all([admin.from("tickets").select("id,seat_id,status,seats!inner(seat_type)").eq("organization_id",p.organization_id).eq("event_id",eventId).eq("person_id",personId).neq("status","cancelled"),admin.from("events").select("free_ticket_quota,paid_ticket_quota,max_guest_tickets").eq("id",eventId).eq("organization_id",p.organization_id).single()]);
 const current=(existing??[]).filter((x:any)=>x.seats?.seat_type===seatType);const quota=seatType==="free_guest"?Number(event?.free_ticket_quota||0):Number(event?.paid_ticket_quota||0);if(count>quota)fail(path,`Requested quantity exceeds the configured ${seatType==="free_guest"?"free":"paid"} quota of ${quota}`);
 if(count<current.length){for(const t of current.slice(count)){await admin.from("tickets").delete().eq("id",t.id);await admin.from("booking_seats").delete().eq("seat_id",t.seat_id);await admin.from("seats").update({status:"available"}).eq("id",t.seat_id)}}
 if(count>current.length){const needed=count-current.length;const {data:available,error}=await admin.from("seats").select("id,code,event_id").eq("organization_id",p.organization_id).eq("event_id",eventId).eq("seat_type",seatType).eq("status","available").order("row_number").order("column_number").limit(needed);if(error||!available||available.length<needed)fail(path,"Not enough available seats for the selected quantity");const {data:person}=await admin.from("people_directory").select("id,profile_id").eq("id",personId).single();const {data:booking,error:be}=await admin.from("bookings").insert({organization_id:p.organization_id,event_id:eventId,user_id:person?.profile_id||null,person_id:personId,status:"confirmed",total_bhd:0,assigned_by_admin:true}).select("id").single();if(be||!booking)fail(path,be?.message||"Could not create booking");for(const seat of available){await admin.from("booking_seats").delete().eq("seat_id",seat.id);const link=await admin.from("booking_seats").insert({booking_id:booking.id,seat_id:seat.id,price_bhd:0});if(link.error)fail(path,link.error.message);const issued=await admin.from("tickets").insert({organization_id:p.organization_id,event_id:eventId,user_id:person?.profile_id||null,person_id:personId,seat_id:seat.id,booking_id:booking.id,status:"valid",assigned_by_admin:true});if(issued.error)fail(path,issued.error.message);await admin.from("seats").update({status:"booked"}).eq("id",seat.id)}}
 done(path,"Guest-seat allocation updated")
}

export async function removeTicketByAdmin(fd:FormData){const p=await requireProfile(["admin","regcom"]);const admin=createAdminClient();const id=uuid(fd.get("ticket_id"));if(!id)fail("/dashboard/bookings","Invalid ticket");const{data:t}=await admin.from("tickets").select("seat_id,booking_id").eq("id",id).eq("organization_id",p.organization_id).single();if(!t)fail("/dashboard/bookings","Ticket not found");await admin.from("tickets").delete().eq("id",id);await admin.from("booking_seats").delete().eq("booking_id",t.booking_id).eq("seat_id",t.seat_id);await admin.from("seats").update({status:"available"}).eq("id",t.seat_id);done("/dashboard/bookings","Seat assignment removed")}

export async function reconcileSeatStatuses(fd:FormData){
 const p=await requireProfile(["admin"]);const eventId=uuid(fd.get("event_id"));if(!eventId)fail("/dashboard/seats","Invalid event");
 const s=await createClient();const{data,error}=await s.rpc("reconcile_event_seat_statuses",{p_event_id:eventId});
 if(error)fail("/dashboard/seats",error.message);done("/dashboard/seats",`${Number(data||0)} stale seat status record(s) repaired`)
}

export async function deleteAuditLog(fd:FormData){
 const p=await requireProfile(["admin"]);const id=uuid(fd.get("id"));if(!id)fail("/dashboard/audit","Invalid audit record");
 const s=await createClient();const{error}=await s.from("audit_log").delete().eq("id",id).eq("organization_id",p.organization_id);
 if(error)fail("/dashboard/audit",error.message);done("/dashboard/audit","Audit record deleted")
}

export async function clearAuditLogs(fd:FormData){
 const p=await requireProfile(["admin"]);const mode=String(fd.get("mode")||"all");const s=await createClient();let q:any=s.from("audit_log").delete().eq("organization_id",p.organization_id);
 if(mode==="older30")q=q.lt("created_at",new Date(Date.now()-30*24*60*60*1000).toISOString());
 const{error}=await q;if(error)fail("/dashboard/audit",error.message);done("/dashboard/audit",mode==="older30"?"Audit records older than 30 days deleted":"All audit records deleted")
}
